POST http://localhost:4000/Account/login2
Content-Type: application/json

{
    "userName":"Davis",
    "password":"As261/1163/2020"
}
###
GET http://localhost:4000/Account/login2
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGF0dXMiOiJ1bnRhc2tlZCIsImlkIjoyLCJpYXQiOjE3MDc2NDI3Mzd9.tiKtq3o6HoYPfS_YR0WsJzVAsGbpE6Nwo9O-J8133Xw


